### ISSUE TITLE
Fix Japanese title in the slide p21

### ISSUE THREAD

**Issue by xerroxcopy** [johnmaeda/designintechreport-2018#2]
The original English title on the slide [page 21](https://johnmaeda.github.io/?lang=en#21) reads: 

> The perception of design and its impact to business is cyclic

which can be translated into Japanese as something like: 

デザインの受け止められ方とそのビジネスへのインパクトは双方向的に影響する ( I know, it's way too long)

However, the current [Japanese title](https://johnmaeda.github.io/?lang=ja#21) reads: 
> 互いに10億を超える人口が

darwin

**Comment by shotamatsuda** [comment]
Thanks for your comment.
Fixed in 01cb7f4dd42cf064572e0fd4616c45a6ae020766
